name: check

on:
  - push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          pip install poetry
          make install
      - name: Set up Postgresql
        uses: harmon758/postgresql-action@v1
        with:
          postgresql version: '11' 
          postgresql password: postgres
      - name: Make db
        run: make build
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres
      - name: Run mypy, linter and pytest
        run: make check
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres
      - name: Publish code coverage
        uses: paambaati/codeclimate-action@v5
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres
        with:
          coverageCommand: make test-coverage
          debug: true 
